blank_issues_enabled: false
contact_links:
  - name: CivFanatics discussion
    url: https://forums.civfanatics.com/forums/civ5-creation-customization.393/
    about: General Civilization V modding discussion and community help
